### ISSUE TITLE
How do I edit the Orbat?

### ISSUE THREAD

**Issue by AxeriusNetwork** [kjellmf/orbat-chart#1]
How do I edit the Orbat?

**Comment by kjellmf** [comment]
This project is primarily a library for drawing ORBAT charts. The demo application don't have any editing capabilities yet.  It just loads a static ORBAT from a json file (https://github.com/kjellmf/orbat-chart/blob/master/orbatchart-ui/src/testorbat.json). Currently I use the demo application for testing out various drawing option.

**Comment by AxeriusNetwork** [comment]
Ah okay, thanks!

**Comment by AxeriusNetwork** [comment]
How would I go about editing the orbat, as I see a few number/text strings, are they important?
`sidc": "10031000181211004600",`
`"id": "u0xGEGuOLzIcIirsioK0h",`

**Comment by kjellmf** [comment]
The `sidc`  property is the Symbol Identification Code used to identify the symbol. To find the correct symbol code you can use my SIDC-picker tool at https://sidc.milsymb.net/#/2525

The `id` property can be any string as long as it is unique within the ORBAT. You can use "1", "2" and so on if you want. The ids I use are automatically generated.
